### ISSUE TITLE
unknown method PrintTabs for service dashboard.Plugin

### ISSUE THREAD

**Issue by lechugaletal** [aquasecurity/starboard-octant-plugin#80]
Hi,

starboard v0.9.2 + starboard-octant-plugin v0.9.2 is not working with octant v0.19.0 / v0.18.0

Plugin Error

getting tabs from plugins: handle object: running on starboard-octant-plugin: printing tabResponse for plugin "starboard-octant-plugin": grpc client print tab: rpc error: code = Unimplemented desc = unknown method PrintTabs for service dashboard.Plugin

No problem with octant v0.16.3.

Any idea would be appreciated.

Thanks.

**Comment by danielpacak** [comment]
👋 @lechugaletal Thank you for reporting this issue. We're aware of that. Octant 0.18+ introduced a non backward compatible change in Go Plugins API in order to support a nice feature of registering multiple tab for a given GVK. To fix that we have to bump up Octant dependency in go.mod. We're going to do that along with the upcoming release of Starboard v0.10.0

**Comment by jisnardo** [comment]
Great job.
